const { Resend } = require("resend");

const resend = new Resend(process.env.RESEND_API_KEY);

const sendEmail = async (to, productName) => {
  try {
    console.log(
      "RESEND KEY:",
      process.env.RESEND_API_KEY ? "Loaded" : "Missing"
    );

    // Generate a unique Order ID
    const orderId = `BRX-${Date.now()}`;

    const data = await resend.emails.send({
      from: "BRIXO Website Builder <onboarding@resend.dev>",
      to: ["visualonvibe@gmail.com"], // Test email (change after verifying your domain)
      subject: `🛒 New Order Received - ${orderId}`,
      text: `Hello,

A new order has been placed through your BRIXO website.

=========================================
           ORDER DETAILS
=========================================

Order ID       : ${orderId}
Product        : ${productName}
Customer Email : ${to}

=========================================

Please log in to your BRIXO dashboard to view and process this order.

This notification was automatically generated by BRIXO Website Builder.

Regards,
BRIXO Team`,
    });

    console.log("EMAIL SENT:", data);

  } catch (error) {
    console.log("EMAIL ERROR:", error.message);
    throw error;
  }
};

module.exports = sendEmail;